/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aplikasimahasiswa;

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

public class Mahasiswa extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        txtNama.setEditable(true);
        txtNama.setTxt(null);
        txtNim.setTxt(null);
        cbJurusan.setSelectedItem(this);
        
    }
    
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTabelModel();
        model.addColumn ("No.");
        model.addColumn ("Nama Mahasiswa");
        model.addColumn ("Nim");
        model.addColumn ("Jurusan");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM Mahasiswa";
            java.sql.Connection conn = (Connection)konfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[] {no++, res.getString(1), {no++, res.getString(2), {no++, res.getString(3)});

}       tabelMahasiswa.setModel(model);

            }
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMassage ());
        }
        
        
    }

    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        txtAplikasiMahasiswa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JButton();
        txtNim = new javax.swing.JButton();
        cbJurusan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        tbCreat = new javax.swing.JButton();
        tbRead = new javax.swing.JButton();
        tbUpdate = new javax.swing.JButton();
        tbDelete = new javax.swing.JButton();
        tbCancel = new javax.swing.JButton();
        tbExit = new javax.swing.JButton();

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mahasiswa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAplikasiMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAplikasiMahasiswa.setText("Aplikasi Mahasiswa");
        getContentPane().add(txtAplikasiMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 41, -1, -1));

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 79, 37, -1));

        jLabel2.setText("Nim");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 107, 37, -1));

        jLabel3.setText("Jurusan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 138, 37, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 79, 293, 22));

        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });
        getContentPane().add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 107, 293, 22));

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistem Informasi", "Manajemen", "Ilmu Komunikasi", "Akuntansi" }));
        getContentPane().add(cbJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 135, 293, -1));

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMahasiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 636, 267));

        tbCreat.setText("Creat");
        tbCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCreatActionPerformed(evt);
            }
        });
        getContentPane().add(tbCreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 181, 75, -1));

        tbRead.setText("Read");
        tbRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbReadActionPerformed(evt);
            }
        });
        getContentPane().add(tbRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 181, 75, -1));

        tbUpdate.setText("Update");
        tbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(tbUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 181, 75, -1));

        tbDelete.setText("Delete");
        tbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(tbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 181, 75, -1));

        tbCancel.setText("Cancel");
        tbCancel.setToolTipText("");
        tbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCancelActionPerformed(evt);
            }
        });
        getContentPane().add(tbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 181, 75, -1));

        tbExit.setText("Exit");
        tbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExitActionPerformed(evt);
            }
        });
        getContentPane().add(tbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 181, 75, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void tbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExitActionPerformed
    
       System.exit(0);
    }//GEN-LAST:event_tbExitActionPerformed

    private void tbCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCreatActionPerformed
    kosongkan_form();
    }//GEN-LAST:event_tbCreatActionPerformed

    private void tbReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbReadActionPerformed
    try {
    String sql = " INSERT INTO Mahasiswa VALUES ('" + txtNama.getText()+"','" txtNim.getText()+"','"cbJurusan.getSelectedItem()+"');"
    java.sql.Connection conn = (Connection)konfig.configDB();
    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
    pstm.execute();
    JOptionPane.showMessageDialog(null, "Proses simpan data Berhasil..");
    tampilkan_data();
    kosongkan_form();
    
    }catch (HeadlessException)| (SQLException e){
   JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_tbReadActionPerformed

    private void tbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdateActionPerformed
    try {
    String sql = "UPDATE Mahasiswa SET nama = '" + txtNama.getText()+"',nim = '" txtNim.getText()+"',Jurusan = '"cbJurusan.getSelectedItem()+"');"
    java.sql.Connection conn = (Connection)konfig.configDB();
    java.sql.PreparedStatement pstm = conn preparedStatement(sql);
    pstm.execute();
    JOptionPane.showMessageDialog (null, "Edit data berhasil..");
   } catch (HeadlessException | SQLException e){
JOptionPane.showMessageDialog (this, e.getMessage());
} 
tampilkan_data();
kosongkan_form();
    }//GEN-LAST:event_tbUpdateActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
    int baris = tabelMahasiswa.rowAtPoint(evt.getPoint());
    String nama = tabelMahasiswa.getValueAt(baris, 1).toString();
    txtNama.setText(nama);

    String nim = tabelMahasiswa.getValueAt(baris, 2).toString();
    txtNim.setText(nim);

    String jurusan = tabelMahasiswa.getValueAt(baris, 3).toString();
    txtJurusan.setText(jurusan);
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    private void tbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDeleteActionPerformed
    try{
String sql = " DELETE FROM Mahasiswa where nama = '" + txtNama.getText()+ "'";
  java.sql.Connection conn = (Connection)konfig.configDB();
    java.sql.PreparedStatement pstm = conn preparedStatement(sql);
    pstm.execute();
    JOptionPane.showMessageDialog (null, "Delete data berhasil..");
}catch (HeadlessException | SQLException e){
JOptionPane.showMessageDialog (this, e.getMessage());
} 
tampilkan_data();
kosongkan_form();
    }       
    }//GEN-LAST:event_tbDeleteActionPerformed

    private void tbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCancelActionPerformed
 kosongkan_form();
    }//GEN-LAST:event_tbCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JButton tbCancel;
    private javax.swing.JButton tbCreat;
    private javax.swing.JButton tbDelete;
    private javax.swing.JButton tbExit;
    private javax.swing.JButton tbRead;
    private javax.swing.JButton tbUpdate;
    private javax.swing.JLabel txtAplikasiMahasiswa;
    private javax.swing.JButton txtNama;
    private javax.swing.JButton txtNim;
    // End of variables declaration//GEN-END:variables
}
